[package]
name = "grep-prop"
version = "0.1.0"
authors = ["Miguel Panuto <miguel.panuto@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
